services:
  astro:
    container_name: ${NAME}-astro
    restart: unless-stopped
    build:
      context: astro
    networks:
      - front
    depends_on:
      - payload

  payload:
    container_name: ${NAME}-payload
    restart: unless-stopped
    build:
      context: payload
    environment:
      NAME: ${NAME}
      PAYLOAD_URL: ${PAYLOAD_URL}
      PAYLOAD_PORT: ${PAYLOAD_PORT}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      TOKEN: ${TOKEN}
    networks:
      - front
      - back
    depends_on:
      - mongo

  mongo:
    container_name: ${NAME}-mongo
    image: mongo:6.0.5
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    command:
      - --storageEngine=wiredTiger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PW}
    networks:
      - back

networks:
  front:
  back:
